apiVersion: apps/v1
kind: Deployment
metadata:
  name: pravega-grpc-gateway
  labels:
    app: {{ .Values.app }}
    component: pravega-grpc-gateway
    release: {{ .Release.Name }}
spec:
  selector:
    matchLabels:
      app: {{ .Values.app }}
      component: pravega-grpc-gateway
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ .Values.app }}
        component: pravega-grpc-gateway
        release: {{ .Release.Name }}
    spec:
      serviceAccount: {{ .Release.Namespace }}-pravega
      containers:
        - name: main
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          imagePullPolicy: Always
          ports:
            - containerPort: 80
              name: http
          env:
            - name: PRAVEGA_CONTROLLER
              value: "{{ .Values.pravega.controller }}"
            - name: pravega_client_auth_method
              value: Bearer
            - name: pravega_client_auth_loadDynamic
              value: "true"
            - name: JAVA_OPTS
              value: "-XshowSettings:vm -Xmx768m"
          resources:
            requests:
              memory: "1536Mi"
              cpu: "1000m"
            limits:
              memory: "1536Mi"
              cpu: "2000m"
